# Generated by Django 3.2.25 on 2024-04-12 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunawaelections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='status',
            field=models.CharField(default='Uploaded', max_length=255),
        ),
    ]
